#!/usr/bin/python3
from jinja2 import *
import os
import argparse
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument('filename')
parser.add_argument('-d', '--data', default = '{}')
parser.add_argument('-o', '--output', default = '/dev/stdout')
parser.add_argument('-f', '--format', default = 'json', choices=['json','yaml','env'])
parser.add_argument('-I', '--include', action='append', default = [])
args = parser.parse_args()

env = Environment(loader=ChoiceLoader([
    FileSystemLoader(Path(args.filename).parent.absolute()),
    *[FileSystemLoader(inc) for inc in args.include]
]))

if args.format == 'json':
    import json
    data = json.loads(args.data)
elif args.format == 'yaml':
    import yaml
    data = yaml.safe_load(args.data)

template = env.get_template(os.path.basename(args.filename))

with open(args.output, "w") as fp:
    fp.write(template.render(**data))