#!/usr/bin/python3
from jinja2 import *
import os
import json
import yaml
import argparse
from pathlib import Path

def lambda_open(filename, effect):
    with open(filename, 'r') as fp:
        return effect(fp)

def xjinja_read_raw(filename):
    return lambda_open("data/" + filename, lambda f : f.read())

def xjinja_read_yaml(filename):
    return lambda_open("data/" + filename, lambda f : yaml.safe_load(f))

def xjinja_read_json(filename):
    return lambda_open("data/" + filename, lambda f : json.load(f))

def xjinja_read_sqlite(filename, table):
    import sqlite3

    with sqlite3.connect("data/" + filename) as db:
        db.row_factory = sqlite3.Row
        cur = db.cursor()
        return cur.execute(f"SELECT * FROM {table}").fetchall()

parser = argparse.ArgumentParser()
parser.add_argument('filename')
parser.add_argument('-o', '--output', default = '/dev/stdout')
parser.add_argument('-I', '--include', action='append', default = [])
args = parser.parse_args()

env = Environment(loader=ChoiceLoader([
    FileSystemLoader(Path(args.filename).parent.absolute()),
    *[FileSystemLoader(inc) for inc in args.include]
]))

template = env.get_template(os.path.basename(args.filename))

with open(args.output, "w") as fp:
    fp.write(template.render(read = {
        'json': xjinja_read_json,
        'yaml': xjinja_read_yaml,
        'sqlite': xjinja_read_sqlite,
        'raw': xjinja_read_raw,
    }))